# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongodb
    ports:
      - 27017:27017
    environment:
      PUID: 1000
      PGID: 1000
    volumes:
      - ./db/mongo:/data/db
